### PR TITLE
Define a working gql schema

### PR DESCRIPTION
**Pull request by lorado**
I thought it would be easier to define working example directly here.
I tested it locally with Altair GraphQL Client and it works as expected. 
You can also see what I meant with manually mutation resolver vs. `@create` + custom arg resolver.
I also added simpleImageUpload as an example of simple image upload.

Feel free to ask questions, if you don't understand any step

### CODE REVIEW

**Comment by wolfiton** [comment]
> I thought it would be easier to define working example directly here.
> I tested it locally with Altair GraphQL Client and it works as expected.
> You can also see what I meant with manually mutation resolver vs. `@create` + custom arg resolver.
> I also added simpleImageUpload as an example of simple image upload.
> 
> Feel free to ask questions, if you don't understand any step

That was my idea from the start to let you guys contribute directly and have a working example that we can reference during the development of this example.
Also thank you for mentioning that graphql client it looks interesting.

**Comment by wolfiton** [comment]
Error-on-image-mutation-createPostWithArgs
I don't understand why this mutation is not working:

```graphql
mutation($image: Upload!){
  createPostWithArgResolver(input:{title:"asd1",content:"test1", image: $image}){
    id
    title
    image
  }
}
```
I defined my $image in Altair using the docs for image upload to graphql

Thanks

**Comment by lorado** [comment]
It is always helpful to read the error message =) It says, that `image` don't have a default value, you also see the SQL query that was executed. Please read my commit messages: https://github.com/wolfiton/vue-upload/pull/1/commits/94cae3bad7571ac14be03244592013f15bba04e0

`@created` executed before arg resolvers, so the Post model is sent to DB without image, because image field is handled separately by arg resolver.

Just run `php artisan migrate:fresh` to run all migrations from start. Then it will work

**Comment by wolfiton** [comment]
I didn't saw any changes made to db that would break the functionality just that you added nullable to image in the post table.
But you are right after migrating fresh now it works.

**Comment by wolfiton** [comment]
One other problem is that I can't find the image path even after I use this command `php artisan storage:link`
I saw that the images uploaded successfully but can't find the path to them.
 tried this on the frontend 
``` js<img                                    
     :src="`http://localhost:8000/public/storage/${post.image}`"
                                    alt="cover image"
                                    style="width:200px"
                                />
```

**Comment by lorado** [comment]
Hehe. Have you worked with Laravel before? When you call `storePublicly('uploads')` publicly only means, that file permissions are more open. But without defining any disk, it will use default disk. By default it is `local` (take a look into `config/filesystems.php`).

`php artisan storage:link` links `storage/app/public` folder, which is a `public` disk. So for image storage you have to select the publik disk. So you have to change storage code to following:

```php
$image->storePublicly('uploads', ['disk' => 'public']);
```

**Comment by wolfiton** [comment]
I made the modifications in the mutations and the directive but see no changes. Also when you first show me that code with store publically I though that there is an automatic resolver for the local disk.

These things should really be presented in the documentation so that everything becomes clear. Also what I am doing now, it should have been done from the start. Because a project without documentation can't be taken seriously the result is that there are no big names using this stack in production.

Why I am saying this?

Because I feel that I am the third wheel in this project and if I am right then I will go my own merry way and not bother with this any further.

Thanks

**Comment by lorado** [comment]
>I made the modifications in the mutations and the directive but see no changes.

You have to upload new files again, as the old uploads are stored in `local` disk, and not `public`. You could also move directory it on your own from `storage/uploads` to `storage/public/uploads`, then old uploads will also become accessable.

> These things should really be presented in the documentation so that everything becomes clear

To be clear - lighthouse is only an additional library for Laravel, so it is possible to use GraphQL within Laravel. Laravel itself is a very huge framework with tons of use cases and additional libraries. Lighthouse is one of them. This "confusion" about storage disks is actually a Laravel knowledge, not lighthouse knowledge. That is why we can't cover everything within lighthouse library. At lighthouse we suggest that user is using Laravel, so he knows how to manage it. If you want to know more about how Laravel file system (storage) works, take a look into the docs: https://laravel.com/docs/7.x/filesystem#introduction
  
> Because I feel that I am the third wheel in this project and if I am right then I will go my own merry way and not bother with this any further.

I am glad to help you. I like your idea, go ahead. But I don't want to implement your project for you. You can ask questions, I will navigate you and give you some doc-links as starting point to dive deeper. So don't get angry =)

**Comment by wolfiton** [comment]
OK,
As a side note this looks odd to me v-for="post of data.posts.data" why wouldn't this be v-for="post of data.posts"?
I can't understand this design decision what advantages it brings?
This comes from here:
```graphql
  query{
    posts{
      data{
        id
        title
        content
        image
      }
    }
  }

```
Thanks

**Comment by lorado** [comment]
This is because you use `@paginate` directive. It gives you ability to query results page by page. You can read here https://lighthouse-php.com/4.12/eloquent/getting-started.html#pagination and here https://lighthouse-php.com/4.12/api-reference/directives.html#paginate

If you want to fetch all the data, you have to use `@all` directive on your field.

Generally you will have to use pagination on blog. At some point you will get much post entries, lets say 1000. You don't want to serve them back all at once, it will load SQL query, Network (to transfer result from server to client), JS on client. That is why you have to paginate your results, and query e.g. 20 items at once.

**Comment by wolfiton** [comment]
So this directive let's me stream my data so i can serve chunks of it.
I finished the upload feature but have some problems with data null in vue. Although the app works.
Thanks

**Comment by lorado** [comment]
I wouldn't call it stream. It is more like:

"Give me 20 entries starting from 10th" -> SQL generates somethinkg like `LIMIT 20 OFFSET 10`
If you want next page, you have to query
"Give me 20 entries starting from 30th" -> SQL goes `LIMIT 20 OFFSET 30`

**Comment by lorado** [comment]
> I think that th error comes from the vue apollo query component that expects data.posts not data.posts.data.

Please try to figure it out on your own. Ill take a look tonight

**Pull request merged**
